@echo Building util...
@cmd /C ant -f util/build.xml %1
@echo Building IET...
@cmd /C ant -f iet/build.xml %1
@echo Building Ex...
@cmd /C ant -f ex/build.xml %1
@echo Building elgwrp...
@cmd /C ant -f elgwrp/build.xml %1
@echo Building hmmwrp...
@cmd /C ant -f hmmwrp/build.xml %1
