echo Building util...
ant -f util/build.xml $1
echo Building IET...
ant -f iet/build.xml $1
echo Building Ex...
ant -f ex/build.xml $1
echo Building elgwrp...
ant -f elgwrp/build.xml $1
echo Building hmmwrp...
ant -f hmmwrp/build.xml $1
