/* Generated By:JavaCC: Do not edit this line. GrmTokenizerConstants.java */
package ex.reader.tokenizer;

public interface GrmTokenizerConstants {

  int EOF = 0;
  int NUMDOTS = 1;
  int FLOAT = 2;
  int INT = 3;
  int ALPHA = 4;
  int ALPHANUM = 5;
  int NUMALPHA = 6;
  int APOS = 7;
  int ACRONYM = 8;
  int COMPANY = 9;
  int EMAIL = 10;
  int HOST = 11;
  int URL = 12;
  int P = 13;
  int SIGN = 14;
  int LETTER = 15;
  int CJK = 16;
  int DIGIT = 17;
  int NOISE = 18;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<NUMDOTS>",
    "<FLOAT>",
    "<INT>",
    "<ALPHA>",
    "<ALPHANUM>",
    "<NUMALPHA>",
    "<APOS>",
    "<ACRONYM>",
    "<COMPANY>",
    "<EMAIL>",
    "<HOST>",
    "<URL>",
    "<P>",
    "<SIGN>",
    "<LETTER>",
    "<CJK>",
    "<DIGIT>",
    "<NOISE>",
  };

}
